/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FUser.h
 *
 * A User who is purchasing from the pet store
 */



#include "ModelBase.h"

#include "FString.h"

namespace model {

/*
 * A User who is purchasing from the pet store
 */
struct  FFUser
    : public FJsonSerializable
{
public:
    BEGIN_JSON_SERIALIZER
        JSON_SERIALIZE("Id", Id);
            JSON_SERIALIZE("Username", Username);
            JSON_SERIALIZE("FirstName", FirstName);
            JSON_SERIALIZE("LastName", LastName);
            JSON_SERIALIZE("Email", Email);
            JSON_SERIALIZE("Password", Password);
            JSON_SERIALIZE("Phone", Phone);
        JSON_SERIALIZE("UserStatus", UserStatus);
    END_JSON_SERIALIZER
private:
     
    int64 Id;
    FString Username;
    FString FirstName;
    FString LastName;
    FString Email;
    FString Password;
    FString Phone;
    int32 UserStatus;
    
};

}

