/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FPetApi.h
 *
 * 
 */


#include "../ApiClient.h"

#include "FApiResponse.h"
#include "FPet.h"
#include "FString.h"
#include "HttpContent.h"



namespace api {

class  FPetApi : public IFPetApi 
{
public:
    DECLARE_DELEGATE_OneParam(FOnAddPet, const & )
    DECLARE_DELEGATE_OneParam(FOnDeletePet, const & )
    DECLARE_DELEGATE_OneParam(FOnFindPetsByStatus, const TArray<FPet>& )
    DECLARE_DELEGATE_OneParam(FOnFindPetsByTags, const TArray<FPet>& )
    DECLARE_DELEGATE_OneParam(FOnGetPetById, const FPet& )
    DECLARE_DELEGATE_OneParam(FOnUpdatePet, const & )
    DECLARE_DELEGATE_OneParam(FOnUpdatePetWithForm, const & )
    DECLARE_DELEGATE_OneParam(FOnUploadFile, const FApiResponse& )
   
    bool AddPet(
        FFPet body
        , const FOnAddPet& SuccessDelegate = FOnAddPet()
    )
   
    bool DeletePet(
        int64 petId,
        FString apiKey
        , const FOnDeletePet& SuccessDelegate = FOnDeletePet()
    )
   
    bool FindPetsByStatus(
        TArray&lt;FString&gt; status
        , const FOnFindPetsByStatus& SuccessDelegate = FOnFindPetsByStatus()
    )
   
    bool FindPetsByTags(
        TArray&lt;FString&gt; tags
        , const FOnFindPetsByTags& SuccessDelegate = FOnFindPetsByTags()
    )
   
    bool GetPetById(
        int64 petId
        , const FOnGetPetById& SuccessDelegate = FOnGetPetById()
    )
   
    bool UpdatePet(
        FFPet body
        , const FOnUpdatePet& SuccessDelegate = FOnUpdatePet()
    )
   
    bool UpdatePetWithForm(
        int64 petId,
        FString name,
        FString status
        , const FOnUpdatePetWithForm& SuccessDelegate = FOnUpdatePetWithForm()
    )
   
    bool UploadFile(
        int64 petId,
        FString additionalMetadata,
        HttpContent file
        , const FOnUploadFile& SuccessDelegate = FOnUploadFile()
    )

void OnAddPetResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnAddPet SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnDeletePetResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnDeletePet SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnFindPetsByStatusResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnFindPetsByStatus SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnFindPetsByTagsResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnFindPetsByTags SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnGetPetByIdResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnGetPetById SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnUpdatePetResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnUpdatePet SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnUpdatePetWithFormResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnUpdatePetWithForm SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnUploadFileResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnUploadFile SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}

