/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PetApi.h
 *
 * 
 */


#include "../ApiClient.h"

#include "ApiResponse.h"
#include "FString.h"
#include "HttpContent.h"
#include "Pet.h"



namespace api {

class  FPetApi : public IPetApi 
{
public:
    DECLARE_DELEGATE_OneParam(FOnAddPet, const & )
    DECLARE_DELEGATE_OneParam(FOnDeletePet, const & )
    DECLARE_DELEGATE_OneParam(FOnFindPetsByStatus, const TArray<Pet>& )
    DECLARE_DELEGATE_OneParam(FOnFindPetsByTags, const TArray<Pet>& )
    DECLARE_DELEGATE_OneParam(FOnGetPetById, const Pet& )
    DECLARE_DELEGATE_OneParam(FOnUpdatePet, const & )
    DECLARE_DELEGATE_OneParam(FOnUpdatePetWithForm, const & )
    DECLARE_DELEGATE_OneParam(FOnUploadFile, const ApiResponse& )
   
    bool AddPet(
        Pet Body
        , const FOnAddPet& SuccessDelegate = FOnAddPet()
    )
   
    bool DeletePet(
        int64 PetId,
        FString ApiKey
        , const FOnDeletePet& SuccessDelegate = FOnDeletePet()
    )
   
    bool FindPetsByStatus(
        TArray&lt;FString&gt; Status
        , const FOnFindPetsByStatus& SuccessDelegate = FOnFindPetsByStatus()
    )
   
    bool FindPetsByTags(
        TArray&lt;FString&gt; Tags
        , const FOnFindPetsByTags& SuccessDelegate = FOnFindPetsByTags()
    )
   
    bool GetPetById(
        int64 PetId
        , const FOnGetPetById& SuccessDelegate = FOnGetPetById()
    )
   
    bool UpdatePet(
        Pet Body
        , const FOnUpdatePet& SuccessDelegate = FOnUpdatePet()
    )
   
    bool UpdatePetWithForm(
        int64 PetId,
        FString Name,
        FString Status
        , const FOnUpdatePetWithForm& SuccessDelegate = FOnUpdatePetWithForm()
    )
   
    bool UploadFile(
        int64 PetId,
        FString AdditionalMetadata,
        HttpContent File
        , const FOnUploadFile& SuccessDelegate = FOnUploadFile()
    )

void OnAddPetResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnAddPet SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnDeletePetResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnDeletePet SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnFindPetsByStatusResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnFindPetsByStatus SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnFindPetsByTagsResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnFindPetsByTags SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnGetPetByIdResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnGetPetById SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnUpdatePetResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnUpdatePet SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnUpdatePetWithFormResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnUpdatePetWithForm SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnUploadFileResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnUploadFile SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}

