/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * StoreApi.h
 *
 * 
 */


#include "../ApiClient.h"

#include "Order.h"
#include "TMap.h"



namespace api {

class  FStoreApi : public IStoreApi 
{
public:
    DECLARE_DELEGATE_OneParam(FOnDeleteOrder, const & )
    DECLARE_DELEGATE_OneParam(FOnGetInventory, const TMap<FString, int32>& )
    DECLARE_DELEGATE_OneParam(FOnGetOrderById, const Order& )
    DECLARE_DELEGATE_OneParam(FOnPlaceOrder, const Order& )
   
    bool DeleteOrder(
        int64 OrderId
        , const FOnDeleteOrder& SuccessDelegate = FOnDeleteOrder()
    )
   
    bool GetInventory(
        , const FOnGetInventory& SuccessDelegate = FOnGetInventory()
    )
   
    bool GetOrderById(
        int64 OrderId
        , const FOnGetOrderById& SuccessDelegate = FOnGetOrderById()
    )
   
    bool PlaceOrder(
        Order Body
        , const FOnPlaceOrder& SuccessDelegate = FOnPlaceOrder()
    )

void OnDeleteOrderResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnDeleteOrder SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnGetInventoryResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnGetInventory SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnGetOrderByIdResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnGetOrderById SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);
void OnPlaceOrderResult(FHttpRequestPtr HttpRequest
        , FHttpResponsePtr HttpResponse
        , bool bSucceeded
        , FOnPlaceOrder SuccessDelegate
        , FPlayFabErrorDelegate ErrorDelegate);

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}

